#!/usr/bin/env ruby

# 以下２行は直接 $ ruby bin/jm.rb で実行したときに必要
lib = File.expand_path('../../lib', __FILE__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)

require "yaml2csv"
require "thor"
require "pry" # TODO: remove this line

module Yaml2csv
  class CLI < Thor
    class_option :help, type: :boolean, aliases: '-h', desc: "Show help message."
    class_option :version, type: :boolean, desc: "Show version."
    default_command :yaml2csv

    desc "yaml2csv", "Convert yaml file to csv string."
    method_option :file, type: :string, aliases: ['-f', '--file']
    def yaml2csv(*args)
      yaml_file_path = options[:file]
      raise "--file <ファイルパス>でファイルを指定してください。" unless yaml_file_path
      Yaml2csv.yaml_to_csv(yaml_file_path)
    end
  end
end

Yaml2csv::CLI.start
